[pytest]
filterwarnings =
    ignore:.*urllib3\[secure\].*:DeprecationWarning
    ignore:.*desired_capabilities has been deprecated.*:DeprecationWarning
    ignore:.*HTTPResponse.getheader\(\) is deprecated.*:DeprecationWarning